[package]
name = "flash"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
flate2 = "1.1"
walkdir = "2.4"
reqwest = { version = "0.12", features = ["multipart", "json"] }
