[package]
name = "flash"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
zip = "0.6"
walkdir = "2.4"
ssh2 = "0.9"
indicatif = "0.18"
rpassword = "7.4.0"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"