[servers.example]
name = "Example Server"
ip = "192.168.1.100"
username = "example"
password = '123'
port = 22
remote_path = "/home/example/uploads"

[servers.home]
name = "Home Server"
ip = "192.168.1.100"
username = "admin"
port = 22
remote_path = "/home/admin"

[default]
server = 'example'